import Utilitarios.Conexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alunos
 */
public class FrmCada_Grupos extends javax.swing.JFrame {
   Conexao con_bd;
    /**
     * Creates new form FrmCada_Grupos
     */
    public FrmCada_Grupos() {
        initComponents();
        con_bd = new Conexao();//iniciar conexão
        //do objeto
        con_bd.conecta();
        //metodo de conexão
        con_bd.executaSQL("select * from grupos order by codigo");
                TxtCodigo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BtnIncluir = new javax.swing.JButton();
        BtnLocalizar = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtGrupo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Grupos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Código:");

        TxtCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));

        BtnIncluir.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        BtnIncluir.setMnemonic('I');
        BtnIncluir.setText("Incluir");
        BtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIncluirActionPerformed(evt);
            }
        });

        BtnLocalizar.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        BtnLocalizar.setMnemonic('L');
        BtnLocalizar.setText("Localizar");
        BtnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLocalizarActionPerformed(evt);
            }
        });

        BtnAlterar.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        BtnAlterar.setMnemonic('A');
        BtnAlterar.setText("Alterar");
        BtnAlterar.setEnabled(false);
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        BtnExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnExcluir.setMnemonic('E');
        BtnExcluir.setText("Excluir");
        BtnExcluir.setEnabled(false);
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnLimpar.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        BtnLimpar.setMnemonic('M');
        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnIncluir)
                .addGap(18, 18, 18)
                .addComponent(BtnLocalizar)
                .addGap(18, 18, 18)
                .addComponent(BtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnLimpar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIncluir)
                    .addComponent(BtnLocalizar)
                    .addComponent(BtnAlterar)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Grupo:");

        TxtGrupo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(TxtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGrupoActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        Limp_Camp();
        
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void BtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIncluirActionPerformed
    int VCodigo=0;
    try {
        VCodigo = Integer.parseInt(TxtCodigo.getText());
    }
    catch (NumberFormatException erro) {
        JOptionPane.showMessageDialog(null, "Favor informar um código do grupo válido!!!");
        TxtCodigo.requestFocus();
        return; 
    }
    if (VCodigo <=0){
        JOptionPane.showMessageDialog(null, "Código do grupo deve ser maior ou igual a 0!!!");
        TxtCodigo.requestFocus();
        return;
    }
    
    if(TxtGrupo.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Favor informar o grupo de produtos!!");
        TxtGrupo.requestFocus();
        return;   
    }
    
    if(TxtGrupo.getText().length()>15){
        JOptionPane.showMessageDialog(null, "Grupo de produtos deve possuir no máximo 15 caracteres!!!");
        TxtGrupo.requestFocus();
        return;
  
    }//GEN-LAST:event_BtnIncluirActionPerformed
 
    String insert_sql = "insert into grupos(codigo, grupo) values (" + TxtCodigo.getText() +",'" + TxtGrupo.getText() + "')";
    try {
    con_bd.statement.executeUpdate(insert_sql);
    JOptionPane.showMessageDialog(null, "Grupo cadastrado com sucesso!");
    Limp_Camp();
  } catch (SQLException ex){
    JOptionPane.showMessageDialog (null, "Código já cadastrado!!","Inclusão", JOptionPane.INFORMATION_MESSAGE);
    TxtCodigo.requestFocus();
    }
  }
  
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        con_bd.desconecta();
    }//GEN-LAST:event_formWindowClosing

    private void BtnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLocalizarActionPerformed
        String VCodigo = JOptionPane.showInputDialog("Informe o CÓDIGO do grupo!!!");
    
        if(VCodigo.equals("")){
            JOptionPane.showMessageDialog (null, "Favor informar o CÓDIGO do grupo!!!");
            return;
    
        }
        try {
            String pesquisa = "select * from grupos where codigo =" + VCodigo;
            con_bd.executaSQL(pesquisa);
            if (con_bd.resultset.first()) {
                TxtCodigo.setText(con_bd.resultset.getString("Codigo"));
                TxtGrupo.setText(con_bd.resultset.getString("Grupo"));
                TxtCodigo.setEnabled(false);
                BtnIncluir.setEnabled(false);
                BtnAlterar.setEnabled(true);
                BtnExcluir.setEnabled(true);
            } else {
             JOptionPane.showMessageDialog (null, "\nNão existe grupo cadastrado com o código informado !!!");
            
        }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog (null, "\nProblema no acesso aos dados! "+erro.getMessage());
            
        }
    }//GEN-LAST:event_BtnLocalizarActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
      if (TxtGrupo.getText().equals("")){
           JOptionPane.showMessageDialog (null, "Grupo de produtos deve possuir no máximo 15 caracteres !!! ");
          TxtGrupo.requestFocus();
          return;
      }
      if (TxtGrupo.getText().length()>15){
           JOptionPane.showMessageDialog (null, "Grupo de produtos deve possuir no máximo 15 caracteres !!! ");
           TxtGrupo.requestFocus();
            return;
      }
      String varsql = "update grupos set grupo='" + TxtGrupo.getText() + "' where codigo =" + TxtCodigo.getText();
      try {
          con_bd.statement.executeUpdate(varsql);
          JOptionPane.showMessageDialog (null, "Dados(s) alterados(s) com sucesso !!! ");
          
          Limp_Camp();
      }catch (SQLException ex){
           JOptionPane.showMessageDialog (null, "Código já cadastrado!!! ", "Alteração", JOptionPane.INFORMATION_MESSAGE );
           TxtCodigo.requestFocus();
          
          
      }
    
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
       String sql = "";
       try {
           int resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja excluir esse grupo ?","Confirmar Exclusão", JOptionPane.YES_NO_OPTION,3);
           if(resposta ==0){
               sql = "delete from grupos where codigo = " + TxtCodigo.getText();
                con_bd.statement.executeUpdate(sql);
                 JOptionPane.showMessageDialog(rootPane,"Exclusão realizada com sucesso!");
                 Limp_Camp();
           }
       }catch (SQLException erro){
             JOptionPane.showMessageDialog (null, "\nErro na exclusão!\nErro:" + erro +"\nComando SQL passado:" + sql);
           
                
               
           
       }
    }//GEN-LAST:event_BtnExcluirActionPerformed
       public void  Limp_Camp(){ 
           TxtCodigo.setText("");
           TxtGrupo.setText("");
           TxtCodigo.setEnabled(true);
           TxtCodigo.requestFocus();
           BtnIncluir.setEnabled(true);
           BtnAlterar.setEnabled(false);
           BtnExcluir.setEnabled(false);
       }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCada_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCada_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCada_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCada_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCada_Grupos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnIncluir;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnLocalizar;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
