/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alunos
 */
public class FRMCalcBasica extends javax.swing.JFrame {

    /**
     * Creates new form FRMCalcBasica
     */
    public FRMCalcBasica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNum1 = new javax.swing.JTextField();
        TxtNum2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtRes = new javax.swing.JTextField();
        BtnMais = new javax.swing.JButton();
        BtnDivisao = new javax.swing.JButton();
        BtnMultiplicacao = new javax.swing.JButton();
        BtnMenos = new javax.swing.JButton();
        BtnExpotenc = new javax.swing.JButton();
        BtnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("1° Número");

        jLabel2.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("2° Número");

        TxtNum1.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        TxtNum1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNum1ActionPerformed(evt);
            }
        });

        TxtNum2.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        TxtNum2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNum2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Resultado");

        TxtRes.setEditable(false);
        TxtRes.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        TxtRes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtResActionPerformed(evt);
            }
        });

        BtnMais.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        BtnMais.setForeground(new java.awt.Color(0, 51, 153));
        BtnMais.setMnemonic('+');
        BtnMais.setText("+");
        BtnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMaisActionPerformed(evt);
            }
        });

        BtnDivisao.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        BtnDivisao.setForeground(new java.awt.Color(0, 51, 153));
        BtnDivisao.setMnemonic('/');
        BtnDivisao.setText("/");
        BtnDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDivisaoActionPerformed(evt);
            }
        });

        BtnMultiplicacao.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        BtnMultiplicacao.setForeground(new java.awt.Color(0, 51, 153));
        BtnMultiplicacao.setMnemonic('*');
        BtnMultiplicacao.setText("*");
        BtnMultiplicacao.setActionCommand("*");
        BtnMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiplicacaoActionPerformed(evt);
            }
        });

        BtnMenos.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        BtnMenos.setForeground(new java.awt.Color(0, 51, 153));
        BtnMenos.setMnemonic('-');
        BtnMenos.setText("-");
        BtnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenosActionPerformed(evt);
            }
        });

        BtnExpotenc.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        BtnExpotenc.setForeground(new java.awt.Color(0, 51, 153));
        BtnExpotenc.setMnemonic('E');
        BtnExpotenc.setText("EXP");
        BtnExpotenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExpotencActionPerformed(evt);
            }
        });

        BtnLimpar.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        BtnLimpar.setForeground(new java.awt.Color(0, 0, 153));
        BtnLimpar.setMnemonic('L');
        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnDivisao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnExpotenc)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtNum2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(BtnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnMais)
                                .addGap(27, 27, 27)
                                .addComponent(BtnMenos)
                                .addGap(29, 29, 29)
                                .addComponent(BtnMultiplicacao)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtRes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(TxtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLimpar)
                    .addComponent(BtnExpotenc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtRes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        BtnMais.getAccessibleContext().setAccessibleName("+");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNum1ActionPerformed

    }//GEN-LAST:event_TxtNum1ActionPerformed

    private void TxtNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNum2ActionPerformed

    private void TxtResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtResActionPerformed

    private void BtnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMaisActionPerformed
        //Declara as variaveis
        float num1, num2, res;
        //Lê os dados digitados
        num1 = Float.parseFloat(TxtNum1.getText());
        num2 = Float.parseFloat(TxtNum2.getText());
        //Calcule
        res = num1 +num2;
        //Exibe
        TxtRes.setText(Float.toString(res));
    }//GEN-LAST:event_BtnMaisActionPerformed

    private void BtnDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDivisaoActionPerformed
    float num1, num2, res;
        //Lê os dados digitados
        num1 = Float.parseFloat(TxtNum1.getText());
        num2 = Float.parseFloat(TxtNum2.getText());
        //Calcule
        res = num1 / num2;
        //Exibe
        TxtRes.setText(Float.toString(res));
    }//GEN-LAST:event_BtnDivisaoActionPerformed

    private void BtnMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiplicacaoActionPerformed
        float num1, num2, res;
        //Lê os dados digitados
        num1 = Float.parseFloat(TxtNum1.getText());
        num2 = Float.parseFloat(TxtNum2.getText());
        //Calcule
        res = num1 * num2;
        //Exibe
        TxtRes.setText(Float.toString(res));
    }//GEN-LAST:event_BtnMultiplicacaoActionPerformed

    private void BtnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenosActionPerformed
        float num1, num2, res;
        //Lê os dados digitados
        num1 = Float.parseFloat(TxtNum1.getText());
        num2 = Float.parseFloat(TxtNum2.getText());
        //Calcule
        res = num1 - num2;
        //Exibe
        TxtRes.setText(Float.toString(res));
    }//GEN-LAST:event_BtnMenosActionPerformed

    private void BtnExpotencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExpotencActionPerformed
    float num1, num2, res;
        //Lê os dados digitados
        num1 = Float.parseFloat(TxtNum1.getText());
        num2 = Float.parseFloat(TxtNum2.getText());
        //Calcule
        res = (float) Math.pow(num1, num2);
        //Exibe
        TxtRes.setText(Float.toString(res));
    }//GEN-LAST:event_BtnExpotencActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        TxtNum1.setText("");
        TxtNum2.setText("");
        TxtRes.setText("");
        TxtNum1.requestFocus();
    }//GEN-LAST:event_BtnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMCalcBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMCalcBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMCalcBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMCalcBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMCalcBasica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDivisao;
    private javax.swing.JButton BtnExpotenc;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnMais;
    private javax.swing.JButton BtnMenos;
    private javax.swing.JButton BtnMultiplicacao;
    private javax.swing.JTextField TxtNum1;
    private javax.swing.JTextField TxtNum2;
    private javax.swing.JTextField TxtRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
