/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author alunos
 */
public class FRMExtenso_Data extends javax.swing.JFrame {

    /**
     * Creates new form FRMExtenso_Data
     */
    public FRMExtenso_Data() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        BtnSair1 = new javax.swing.JButton();
        Txtdia = new javax.swing.JTextField();
        Txtmes = new javax.swing.JTextField();
        Txtano = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnLimpar = new javax.swing.JButton();
        BtnCalcular = new javax.swing.JButton();
        LblExtenso = new javax.swing.JLabel();
        BtnSair2 = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        BtnSair1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnSair1.setMnemonic('S');
        BtnSair1.setText("Sair");
        BtnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSair1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gera Extenso de Data");

        Txtdia.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        Txtdia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txtdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtdiaActionPerformed(evt);
            }
        });

        Txtmes.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        Txtmes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txtmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtmesActionPerformed(evt);
            }
        });

        Txtano.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        Txtano.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txtano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtanoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Dia");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mês");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Ano");

        BtnLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnLimpar.setMnemonic('L');
        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        BtnCalcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnCalcular.setMnemonic('P');
        BtnCalcular.setText("Processar");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        LblExtenso.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LblExtenso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BtnSair2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BtnSair2.setMnemonic('S');
        BtnSair2.setText("Sair");
        BtnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSair2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnSair2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnCalcular)
                                .addGap(69, 69, 69)
                                .addComponent(LblExtenso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8)))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txtano, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(Txtdia)
                                    .addComponent(Txtmes))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txtdia)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txtano)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblExtenso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLimpar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnCalcular, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28)
                .addComponent(BtnSair2)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtdiaActionPerformed
  
    }//GEN-LAST:event_TxtdiaActionPerformed

    private void TxtmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtmesActionPerformed

    private void TxtanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtanoActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        Txtdia.setText("");
        Txtmes.setText("");
        Txtano.setText("");
        LblExtenso.setText("");
        Txtdia.requestFocus();
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
            //Declara as variaveis
            int dia, mes, ano;
            String E_Dia = "", E_Mes="", Extenso = "Orlândia-SP, ";        
            try{
                   dia = Integer.parseInt(Txtdia.getText());     
                   if (dia < 1 || dia > 31) {
                        JOptionPane.showMessageDialog(null, "Dia deve ser de 1 a 31 !!!");
                        Txtdia.requestFocus();
                        return;            
                   }
                   
            } catch (NumberFormatException e) {      
                  JOptionPane.showMessageDialog(null, "Favor informar um dia válido !!!");
                  Txtdia.requestFocus();
                  return;
            }
               
            try{
                   mes = Integer.parseInt(Txtmes.getText());
                   if (mes < 1 || mes > 12) {
                        JOptionPane.showMessageDialog(null, "Mês deve ser de 1 a 12 !!!");
                        Txtmes.requestFocus();
                         return;            
                   }    
            } catch (NumberFormatException e) {
                  JOptionPane.showMessageDialog(null, "Favor informar um mes válido !!!");
                  Txtmes.requestFocus();
                  return;
            }
               
           try{
                   ano = Integer.parseInt(Txtano.getText());
                   if (ano < 1900) {
                        JOptionPane.showMessageDialog(null, "Ano deve ser de 1900 em diante !!!");
                        Txtano.requestFocus();
                        return;            
                  }
            } catch (NumberFormatException e) {
                  JOptionPane.showMessageDialog(null, "Favor informar um ano válido !!!");
                  Txtano.requestFocus();
                  return;
            }
    
           if ((mes == 04 || mes== 6 || mes== 9 || mes== 11) && dia > 30) {                     
                    JOptionPane.showMessageDialog(null, "Mês possui no máximo 30 dias !!!");
                    Txtdia.requestFocus();
                    return;       
           }
           
           if (mes==2) {
               if (ano % 4 == 0) {
                      if (dia  > 29) {
                        JOptionPane.showMessageDialog(null, "Dia deve ser de 1 a 29 !!!");
                        Txtdia.requestFocus();
                        return;            
                      }
               } else {
                      if (dia  > 28) {
                        JOptionPane.showMessageDialog(null, "Dia deve ser de 1 a 28 !!!");
                        Txtdia.requestFocus();
                        return;            
                      }
               }
           } 
           if (dia==1) {
               E_Dia = "Primeiro";        
               Extenso = Extenso + "Primeiro";
           }
           if (dia==2) {
               E_Dia = "Dois";               
           }
           if (dia==3) {
               E_Dia = "Três";               
           }
           if (dia==4) {
               E_Dia = "Quatro";               
           }
           if (dia==5) {
               E_Dia = "Cinco";               
           }
           if (dia==6) {
               E_Dia = "Seis";               
           }
           if (dia==7) {
               E_Dia = "Sete";               
           }
           if (dia==8) {
               E_Dia = "Oito";               
           }
           if (dia==9) {
               E_Dia = "Nove";               
           }
           if (dia==10) {
               E_Dia = "Dez";               
           }
           if (dia==11) {
               E_Dia = "Onze";               
           }
           if (dia==12) {
               E_Dia = "Doze";               
           }
           if (dia==13) {
               E_Dia = "Treze";               
           }
           if (dia==14) {
               E_Dia = "Quatorze";               
           }
           if (dia==15) {
               E_Dia = "Quinze";               
           }
           if (dia==16) {
               E_Dia = "Dezesseis";               
           }
           if (dia==17) {
               E_Dia = "Dezessete";               
           }
           if (dia==18) {
               E_Dia = "Dezoito";               
           }
           if (dia==19) {
               E_Dia = "Dezenove";               
           }
           if (dia==20) {
               E_Dia = "Vinte";               
           }
           if (dia==21) {
               E_Dia = "Vinte e Um";               
           }
           if (dia==22) {
               E_Dia = "Vinte e Dois";               
           }
           if (dia==23) {
               E_Dia = "Vinte e Três";               
           }
           if (dia==24) {
               E_Dia = "Vinte e Quatro";               
           }
           if (dia==25) {
               E_Dia = "Vinte e Cinco";               
           }
           if (dia==26) {
               E_Dia = "Vinte e Seis";               
           }
           if (dia==27) {
               E_Dia = "Vinte e Sete";               
           }
           if (dia==28) {
               E_Dia = "Vinte e Oito";               
           }
           if (dia==29) {
               E_Dia = "Vinte e Nove";               
           }
           if (dia==30) {
               E_Dia = "Trinta";               
           }
           if (dia==31) {
               E_Dia = "Trinta e Um";               
           }
           if (mes==1) {
               E_Mes = "Janeiro";         
               Extenso = Extenso + " de Janeiro de ";
           }
           if (mes==2) {
               E_Mes = "Fevereiro";          
           }
           if (mes==3) {
               E_Mes = "Março";          
           }
           if (mes==4) {
               E_Mes = "Abril";          
           }
           if (mes==5) {
               E_Mes = "Maio";          
           }
           if (mes==6) {
               E_Mes = "Junho";          
           }
           if (mes==7) {
               E_Mes = "Julho";          
           }
           if (mes==8) {
               E_Mes = "Agosto";          
           }
           if (mes==9) {
               E_Mes = "Setembro";          
           }
           if (mes==10) {
               E_Mes = "Outubro";          
           }
           if (mes==11) {
               E_Mes = "Novembro";          
           }
           if (mes==12) {
               E_Mes = "Dezembro";          
           }
           Extenso = Extenso + Txtano.getText();
           //LblExtenso.setText(Extenso);
           LblExtenso.setText("Orlândia-SP, " + E_Dia + " de " + E_Mes + " de " + Txtano.getText());
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void BtnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSair1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSair1ActionPerformed

    private void BtnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSair2ActionPerformed
    System.exit(0);
    }//GEN-LAST:event_BtnSair2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMExtenso_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMExtenso_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMExtenso_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMExtenso_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMExtenso_Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnSair1;
    private javax.swing.JButton BtnSair2;
    private javax.swing.JLabel LblExtenso;
    private javax.swing.JTextField Txtano;
    private javax.swing.JTextField Txtdia;
    private javax.swing.JTextField Txtmes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
