
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alunos
 */
public class FrmMenus extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenus
     */
    public FrmMenus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuAplicativos = new javax.swing.JMenu();
        OpcSoma = new javax.swing.JMenuItem();
        OpcCalc_Compra = new javax.swing.JMenuItem();
        OpcExtenso_Data = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        OpcSair = new javax.swing.JMenuItem();
        OpcBloco_De_Notas = new javax.swing.JMenu();
        OpcBlocodeNotas = new javax.swing.JMenuItem();
        OpcCalculadora = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estudo de Menus");

        MnuAplicativos.setMnemonic('A');
        MnuAplicativos.setText("Aplicativos");

        OpcSoma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        OpcSoma.setText("Soma");
        OpcSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcSomaActionPerformed(evt);
            }
        });
        MnuAplicativos.add(OpcSoma);

        OpcCalc_Compra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        OpcCalc_Compra.setText("Calculo de Compra Parcelada");
        OpcCalc_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcCalc_CompraActionPerformed(evt);
            }
        });
        MnuAplicativos.add(OpcCalc_Compra);

        OpcExtenso_Data.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        OpcExtenso_Data.setText("Extenso Data");
        OpcExtenso_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcExtenso_DataActionPerformed(evt);
            }
        });
        MnuAplicativos.add(OpcExtenso_Data);
        MnuAplicativos.add(jSeparator1);

        OpcSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        OpcSair.setText("Sair");
        OpcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcSairActionPerformed(evt);
            }
        });
        MnuAplicativos.add(OpcSair);

        jMenuBar1.add(MnuAplicativos);

        OpcBloco_De_Notas.setMnemonic('U');
        OpcBloco_De_Notas.setText("Utilitários");

        OpcBlocodeNotas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        OpcBlocodeNotas.setText("Bloco de Notas");
        OpcBlocodeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcBlocodeNotasActionPerformed(evt);
            }
        });
        OpcBloco_De_Notas.add(OpcBlocodeNotas);

        OpcCalculadora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        OpcCalculadora.setText("Calculadora");
        OpcCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcCalculadoraActionPerformed(evt);
            }
        });
        OpcBloco_De_Notas.add(OpcCalculadora);

        jMenuBar1.add(OpcBloco_De_Notas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OpcCalc_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcCalc_CompraActionPerformed
     FrmCalc_Compra_Parc FrmCalc_Compra_Parc = new FrmCalc_Compra_Parc();
     FrmCalc_Compra_Parc.setVisible (true);
    }//GEN-LAST:event_OpcCalc_CompraActionPerformed

    private void OpcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_OpcSairActionPerformed

    private void OpcSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcSomaActionPerformed
        FrmSoma Frm_Soma = new FrmSoma();
        Frm_Soma.setVisible(true);
    }//GEN-LAST:event_OpcSomaActionPerformed

    private void OpcExtenso_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcExtenso_DataActionPerformed
        FRMExtenso_Data FRMExtensoData = new FRMExtenso_Data();
        FRMExtensoData.setVisible (true);
    }//GEN-LAST:event_OpcExtenso_DataActionPerformed

    private void OpcBlocodeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcBlocodeNotasActionPerformed
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException ex) {
            Logger.getLogger(FrmMenus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OpcBlocodeNotasActionPerformed
          
    
    private void OpcCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcCalculadoraActionPerformed
        try {
            Runtime.getRuntime().exec("notepad");
        } catch (IOException ex) {
            Logger.getLogger(FrmMenus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OpcCalculadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnuAplicativos;
    private javax.swing.JMenu OpcBloco_De_Notas;
    private javax.swing.JMenuItem OpcBlocodeNotas;
    private javax.swing.JMenuItem OpcCalc_Compra;
    private javax.swing.JMenuItem OpcCalculadora;
    private javax.swing.JMenuItem OpcExtenso_Data;
    private javax.swing.JMenuItem OpcSair;
    private javax.swing.JMenuItem OpcSoma;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
