
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alunos
 */
public class FrmCalc_Compra_Parc extends javax.swing.JFrame {

    /**
     * Creates new form FrmCalc_Compra_Parc
     */
    public FrmCalc_Compra_Parc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnCalcular = new javax.swing.JButton();
        BtnLimpar = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        Txtnum1 = new javax.swing.JTextField();
        Txtcliente1 = new javax.swing.JTextField();
        Txtnum2 = new javax.swing.JTextField();
        Txtnum3 = new javax.swing.JTextField();
        Txtres2 = new javax.swing.JTextField();
        Txtres1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Cliente");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Valor Compra");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Valor do Acréscimo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Nº Parcelas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Valor a Pagar");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Valor da Parcela");

        BtnCalcular.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        BtnCalcular.setForeground(new java.awt.Color(0, 102, 102));
        BtnCalcular.setMnemonic('C');
        BtnCalcular.setText("Calcular");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        BtnLimpar.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        BtnLimpar.setForeground(new java.awt.Color(0, 102, 102));
        BtnLimpar.setMnemonic('L');
        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        BtnSair.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        BtnSair.setForeground(new java.awt.Color(0, 102, 102));
        BtnSair.setMnemonic('S');
        BtnSair.setText("Sair");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        Txtnum1.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        Txtnum1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txtnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtnum1ActionPerformed(evt);
            }
        });

        Txtcliente1.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        Txtcliente1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txtcliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtcliente1ActionPerformed(evt);
            }
        });

        Txtnum2.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        Txtnum2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txtnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtnum2ActionPerformed(evt);
            }
        });

        Txtnum3.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        Txtnum3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txtnum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtnum3ActionPerformed(evt);
            }
        });

        Txtres2.setEditable(false);
        Txtres2.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        Txtres2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txtres2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtres2ActionPerformed(evt);
            }
        });

        Txtres1.setEditable(false);
        Txtres1.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        Txtres1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txtres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtres1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)
                                .addComponent(Txtcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txtnum3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txtres1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txtnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txtnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(BtnCalcular)
                        .addGap(35, 35, 35)
                        .addComponent(BtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Txtres2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Txtcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Txtnum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txtnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txtnum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(Txtres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(Txtres2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCalcular)
                    .addComponent(BtnLimpar)
                    .addComponent(BtnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
        //Declara as variaveis
        float num1, num2, num3, res1, res2;
      
        
           
          if (Txtcliente1.getText().isEmpty()) {
                     JOptionPane.showMessageDialog(null, "Favor informar o nome do cliente !!!");
                     Txtcliente1.requestFocus();
                     return;   
                }                
            
               try{
                   num1 = Float.parseFloat(Txtnum1.getText());
               } catch (NumberFormatException e) {
                  JOptionPane.showMessageDialog(null, "Favor informar um valor de compra válido !!!");
                  Txtnum1.requestFocus();
                  return;
               }
               
               try{
                   num2 = Float.parseFloat(Txtnum2.getText());
               } catch (NumberFormatException e) {
                  JOptionPane.showMessageDialog(null, "Favor informar um valor de acréscimo válido !!!");
                  Txtnum2.requestFocus();
                  return;
               }
           
               try{
                   num3 = Integer.parseInt(Txtnum3.getText());
               } catch (NumberFormatException e) {
                  JOptionPane.showMessageDialog(null, "Favor informar uma quantidade de parcelas válida !!!");
                  Txtnum3.requestFocus();
                  return;
               }    
        
        //Calcule
        res1 = num1 + num2;
        res2 = res1 / num3;
        
        //Exibe
        Txtres1.setText(Float.toString(res1));
        Txtres2.setText(Float.toString(res2));
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        Txtcliente1.setText("");
        Txtnum1.setText("");
        Txtnum2.setText("");
        Txtnum3.setText("");
        Txtres1.setText("");
        Txtres2.setText("");
        Txtnum1.requestFocus();
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        System.exit(0);

    }//GEN-LAST:event_BtnSairActionPerformed

    private void Txtnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtnum1ActionPerformed

    }//GEN-LAST:event_Txtnum1ActionPerformed

    private void Txtcliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtcliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtcliente1ActionPerformed

    private void Txtnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtnum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtnum2ActionPerformed

    private void Txtnum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtnum3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtnum3ActionPerformed

    private void Txtres2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtres2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtres2ActionPerformed

    private void Txtres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtres1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCalc_Compra_Parc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCalc_Compra_Parc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCalc_Compra_Parc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCalc_Compra_Parc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCalc_Compra_Parc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnSair;
    private javax.swing.JTextField Txtcliente1;
    private javax.swing.JTextField Txtnum1;
    private javax.swing.JTextField Txtnum2;
    private javax.swing.JTextField Txtnum3;
    private javax.swing.JTextField Txtres1;
    private javax.swing.JTextField Txtres2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
